FROM php:7.4-fpm

RUN set -eux; \
    apt-get update && apt-get install -y \
        wait-for-it \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        zip \
        unzip; \
    docker-php-ext-configure gd --with-freetype --with-jpeg; \
    docker-php-ext-install -j$(nproc) gd pdo_mysql; \
    pecl install xdebug-2.9.8; \
    docker-php-ext-enable xdebug

# COPY --from=composer:1.10.20 /usr/bin/composer /usr/bin/composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY ./artifact /var/www/html
