name: Deploy to test cluster

on:
  push:
    branches:
      - develop
  pull_request:
    types: [synchronize]

jobs:
  npm-operation:
    uses: akvo/main-github-workflow/.github/workflows/npm-operation.yml@main
    secrets: inherit
    with:
      node-version: "16"
      npm-command: "npm i && touch .env && echo MIX_PUBLIC_URL=https://crisis-response.akvotest.org > .env && npm run prod"
  build-push-fpm:
    needs: npm-operation
    uses: akvo/main-github-workflow/.github/workflows/build-push.yml@main
    secrets: inherit
    with:
      app-name: "crisis-response"
      service-name: "main-app-fpm"
      dockerfile-location: ".docker/Dockerfile-php-server"
  build-push-nginx:
    needs: npm-operation
    uses: akvo/main-github-workflow/.github/workflows/build-push.yml@main
    secrets: inherit
    with:
      app-name: "crisis-response"
      service-name: "main-app-nginx"
      dockerfile-location: ".docker/Dockerfile-nginx-server"
  rollout-fpm:
    needs: build-push-fpm
    uses: akvo/main-github-workflow/.github/workflows/rollout.yml@main
    secrets: inherit
    with:
      app-name: "crisis-response"
      service-name: "main-app-fpm"
      cluster-name: "test"
  rollout-nginx:
    needs: build-push-nginx
    uses: akvo/main-github-workflow/.github/workflows/rollout.yml@main
    secrets: inherit
    with:
      app-name: "crisis-response"
      service-name: "main-app-nginx"
      change-name: "test"
